### ISSUE TITLE
node category

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#14] opened 2018-05-15 20:13 UTC
In version 0.6, Michel Dumontier commented:
node category: why not @type ?

**Comment by edeutsch** [comment] 2018-05-15 20:14
I changed this to just "type" in version 0.7.0, to match what we have already implemented at RTX.
But the issue is still open.

**Comment by patrickkwang** [comment] 2019-07-22 19:54
At this point, we can call this a duplicate of #1.

**Closed by patrickkwang** 2019-07-22 19:54 UTC
